<a href="https://colab.research.google.com/github/Tahaa1995/CE888/blob/master/Lab_01/Lab_1_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import numpy as np

t = np.linspace(0, 2*np.pi, 50)
x = np.sin(t)
y = np.cos(t)

In [2]:
#Tasks_1
a = np.array([[ 1, 2, 3, 4],
              [1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [3]:
#Task_2_a

a = np.array([8, 5, 6, 3, 9, 1, 4, 2, 7, 0])

# Sort in ascending order
sorted_array = np.sort(a)
print(sorted_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Task_2_b
a = np.array([8, 5, 6, 3, 9, 1, 4, 2, 7, 0])

#sorted in decending order
reverse_array = sorted_array[::-1]
print(reverse_array)

[9 8 7 6 5 4 3 2 1 0]


In [5]:
a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a)

[1 2 3 4 5 6 7 8 9]


In [6]:
#Task_3

a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.resize(a, 9).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Task_4_a

a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([9,8,7,6,5,4,3,2,1])
#horizontal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [8]:
#Task_4_b

#vertical
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [9]:
#Task_5

a = np.array([5,6,7,8,9,1])
b = np.array([1,2,3,4,5,6])

list(set(a).intersection(b))

[1, 5, 6]

In [10]:
#Task_6

a = np.random.randint(0, 10, (5,5))
print(a)

print("")
print("for Row:")
print(f"Minimum: {a.min(axis=1)}, maximum: {a.max(axis=1)}")

print("")
print("For coluomn:")
print(f"Minimum: {a.min(axis=0)}, maximum: {a.max(axis=0)}")

[[5 4 9 4 4]
 [7 3 2 2 9]
 [1 6 2 7 9]
 [0 4 5 0 9]
 [8 7 6 0 4]]

for Row:
Minimum: [4 2 1 0 0], maximum: [9 9 9 9 8]

For coluomn:
Minimum: [0 3 2 0 4], maximum: [8 7 9 7 9]


In [11]:
#Task_7

a = np.random.randint(0, 10, (100))
print(a)
print("")

print(f"Mean: {a.mean()}, Median: {np.median(a)}, Standard Deviation: {a.std()}")

[0 5 5 3 4 4 6 3 5 7 5 7 1 8 9 2 1 8 0 0 3 8 9 7 7 2 7 9 7 9 3 4 3 6 2 8 4
 2 9 1 3 9 5 1 7 6 9 4 8 9 5 4 0 0 9 0 5 5 3 3 6 8 0 3 2 7 2 7 8 0 6 8 0 2
 0 4 4 5 8 2 5 0 5 4 7 3 2 3 5 3 1 1 9 9 9 9 7 2 9 5]

Mean: 4.68, Median: 5.0, Standard Deviation: 2.935574901105404


In [12]:
#Task_8

a = np.random.random((5,5))
print(a)
print("")

max, min = a.max(), a.min()
a = (a - min)/(max - min)

print("normalization:")
print(a)

[[0.25283827 0.26782751 0.64634317 0.47811835 0.34851604]
 [0.09577718 0.60618154 0.63719482 0.22163776 0.66683733]
 [0.61158257 0.85183909 0.25466504 0.87366497 0.33403157]
 [0.74828856 0.94553303 0.64585058 0.28494554 0.48726097]
 [0.81226524 0.22630158 0.97314636 0.6852233  0.80791435]]

normalization:
[[0.17901369 0.19609799 0.62751918 0.4357814  0.28806444]
 [0.         0.58174412 0.61709216 0.14345225 0.65087784]
 [0.58790006 0.86173748 0.18109579 0.886614   0.27155546]
 [0.74371359 0.96852713 0.62695774 0.21560862 0.44620189]
 [0.81663236 0.14876793 1.         0.67183363 0.81167334]]


In [13]:
#Task_9

a = np.random.randint(0, 10, (3,4,4))
print("a=",a)
print("")

b = np.random.randint(0, 10, (4,4))
print("b=",b)
print("")

c = a*b
print("c=",c)

a= [[[3 4 1 4]
  [8 1 9 1]
  [3 4 8 2]
  [1 4 1 6]]

 [[5 3 3 2]
  [6 4 7 3]
  [0 0 9 6]
  [0 1 3 9]]

 [[2 6 4 3]
  [8 2 1 6]
  [6 8 5 4]
  [0 0 9 1]]]

b= [[3 0 9 7]
 [1 7 6 9]
 [7 2 5 8]
 [1 8 7 8]]

c= [[[ 9  0  9 28]
  [ 8  7 54  9]
  [21  8 40 16]
  [ 1 32  7 48]]

 [[15  0 27 14]
  [ 6 28 42 27]
  [ 0  0 45 48]
  [ 0  8 21 72]]

 [[ 6  0 36 21]
  [ 8 14  6 54]
  [42 16 25 32]
  [ 0  0 63  8]]]
