<a href="https://colab.research.google.com/github/Tahaa1995/CE888/blob/master/Lab1/Lab_1_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import numpy as np

t = np.linspace(0, 2*np.pi, 50)
x = np.sin(t)
y = np.cos(t)

In [0]:
#Tasks_1
a = np.array([[ 1, 2, 3, 4],
              [1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [0]:
#Task_2_a

a = np.array([8, 5, 6, 3, 9, 1, 4, 2, 7, 0])

# Sort in ascending order
sorted_array = np.sort(a)
print(sorted_array)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
#Task_2_b
a = np.array([8, 5, 6, 3, 9, 1, 4, 2, 7, 0])

#sorted in decending order
reverse_array = sorted_array[::-1]
print(reverse_array)

[9 8 7 6 5 4 3 2 1 0]


In [0]:
a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a)

[1 2 3 4 5 6 7 8 9]


In [0]:
#Task_3

a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.resize(a, 9).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#Task_4_a

a = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([9,8,7,6,5,4,3,2,1])
#horizontal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [0]:
#Task_4_b

#vertical
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [0]:
#Task_5

a = np.array([5,6,7,8,9,1])
b = np.array([1,2,3,4,5,6])

list(set(a).intersection(b))

[1, 5, 6]

In [0]:
#Task_6

a = np.random.randint(0, 10, (5,5))
print(a)

print("")
print("for Row:")
print(f"Minimum: {a.min(axis=1)}, maximum: {a.max(axis=1)}")

print("")
print("For coluomn:")
print(f"Minimum: {a.min(axis=0)}, maximum: {a.max(axis=0)}")

[[0 2 4 1 8]
 [7 6 7 6 4]
 [9 3 9 6 7]
 [5 3 6 9 2]
 [5 4 2 0 6]]

for Row:
Minimum: [0 4 3 2 0], maximum: [8 7 9 9 6]

For coluomn:
Minimum: [0 2 2 0 2], maximum: [9 6 9 9 8]


In [0]:
#Task_7

a = np.random.randint(0, 10, (100))
print(a)
print("")

print(f"Mean: {a.mean()}, Median: {np.median(a)}, Standard Deviation: {a.std()}")

[3 9 7 8 8 8 1 5 7 7 9 8 4 3 7 2 8 9 3 0 8 1 2 8 1 1 4 9 2 9 2 7 9 3 2 2 8
 9 1 8 7 1 2 9 6 6 7 2 4 7 3 5 0 8 5 3 4 5 6 8 0 8 7 9 8 1 5 7 9 7 4 5 1 1
 7 8 2 1 6 7 5 9 0 5 7 2 6 9 1 9 4 4 7 4 8 1 1 6 1 9]

Mean: 5.11, Median: 5.5, Standard Deviation: 2.9492202359267776


In [0]:
#Task_8

a = np.random.random((5,5))
print(a)
print("")

max, min = a.max(), a.min()
a = (a - min)/(max - min)

print("normalization:")
print(a)

[[0.48526296 0.99702338 0.99894733 0.18166827 0.94775008]
 [0.85014727 0.65848021 0.69275179 0.07134769 0.24526773]
 [0.02238983 0.2713305  0.52061597 0.37212985 0.71292679]
 [0.1469655  0.47958679 0.94267424 0.65897322 0.27413923]
 [0.08538841 0.7506396  0.79055474 0.34912256 0.11693832]]

normalization:
[[0.47398451 0.99802986 1.         0.16310196 0.94757374]
 [0.84762796 0.65135988 0.68645417 0.05013311 0.22822814]
 [0.         0.25491656 0.51018618 0.35813562 0.70711346]
 [0.12756614 0.46817208 0.94237606 0.65186472 0.25779271]
 [0.06451088 0.74573158 0.78660489 0.33457603 0.09681815]]


In [0]:
#Task_9

a = np.random.randint(0, 10, (3,4,4))
print("a=",a)
print("")

b = np.random.randint(0, 10, (4,4))
print("b=",b)
print("")

c = a*b
print("c=",c)

a= [[[6 1 8 1]
  [3 1 9 3]
  [0 3 3 3]
  [7 1 3 3]]

 [[4 3 4 9]
  [8 8 0 8]
  [0 8 6 6]
  [0 3 4 7]]

 [[1 1 0 6]
  [9 6 6 8]
  [2 0 5 8]
  [2 0 6 6]]]

b= [[3 0 4 0]
 [9 3 1 8]
 [7 2 5 9]
 [4 1 6 1]]

c= [[[18  0 32  0]
  [27  3  9 24]
  [ 0  6 15 27]
  [28  1 18  3]]

 [[12  0 16  0]
  [72 24  0 64]
  [ 0 16 30 54]
  [ 0  3 24  7]]

 [[ 3  0  0  0]
  [81 18  6 64]
  [14  0 25 72]
  [ 8  0 36  6]]]
